### ISSUE TITLE
Printing map fields returns {}

### ISSUE THREAD

**Issue by sadaaithal** [smil2k/resurrect-java#3]
resurrect java> obj.earlierVer
object com.ssd.ReleaseVersion{3315254688}{[versionString, name, ordinal]}
resurrect java> obj.serviceAdminMap
{}

serviceAdminMap is of type java.util.concurrent.ConcurrentHashMap
Any idea how I can add a handler to print such collections?

**Comment by smil2k** [comment]
There is a ConcurrentHashMap parser already, maybe the implementation has been changed in your JDK since openjdk7. 

describeObject(factory.getRawObject(objId)) would return the original object as-is. Check whether it has a "segments" field plus tables in the segments. This was the case in openjdk7. 

I think the best would be to autodetect the internal structure inside the handler and use the right strategy to extract the data.

This is where the handler is placed:
https://github.com/smil2k/resurrect-java/blob/master/resurrectjava/src/main/resources/library/04_openjdk7.js

Handlers does not change anything in the dump nor in memory. You can reinterpret it using the "." or "source" command, this helps with implementing the parsing. 

If you were able to fix the handler, please consider making a pull request.

**Comment by smil2k** [comment]
Yes, layout has been changed:

https://github.com/openjdk/jdk/blob/master/src/java.base/share/classes/java/util/concurrent/ConcurrentHashMap.java

You need to check whether it has "segments", then process them. Next check for "table" and "nextTable", and add all key-values as you saw in the previous example.

**Comment by smil2k** [comment]
Were you able to proceed with this?

**Comment by sadaaithal** [comment]
yes @smil2k  ( sorry for the delay )
i got it done differently from the other tool i am working on which uses https://github.com/aragozin/heaplib

**Comment by smil2k** [comment]
Thank you. I keep it open, because ConcurrentHashMAp is not ok.
